#!/bin/bash

pageSize=$(cat resume.json | jq -r '.layout.pdf.size')

leftMargin=$(cat resume.json | jq '.layout.pdf.margins.left')
rightMargin=$(cat resume.json | jq '.layout.pdf.margins.right')
topMargin=$(cat resume.json | jq '.layout.pdf.margins.top')
bottomMargin=$(cat resume.json | jq '.layout.pdf.margins.bottom')

sourceFile=$(cat resume.json | jq -r '.layout.pdf.source')
destinationFile=$(cat resume.json | jq -r '.layout.pdf.destination')

wkhtmltopdf \
	--page-size $pageSize \
	-L $leftMargin -R $rightMargin -T $topMargin -B $bottomMargin \
	$sourceFile \
	$destinationFile
